apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finflow
resources:
  - namespace.yaml
  - configmap.yaml
  - gateway.yaml
  - payment-service.yaml
  - ledger-service.yaml
  - outbox-publisher.yaml
  - ledger-consumer.yaml
images:
  - name: finflow/gateway-service
    newTag: dev
  - name: finflow/payment-service
    newTag: dev
  - name: finflow/ledger-service
    newTag: dev
